# Generated by Django 4.2.7 on 2023-11-21 02:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dannyapp", "0002_leet_tags_thoughts_tags"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Homepage",
            new_name="Index",
        ),
    ]
